server:
  port: 8080
  servlet:
    context-path: /procurement

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  expiration: ${JWT_EXPIRATION}

app:
  security:
    admin:
      username: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:ChangeMeInEnv}
      email: ${ADMIN_EMAIL:admin@epms.com}
    manager:
      username: ${MANAGER_USERNAME:manager}
      password: ${MANAGER_PASSWORD:ChangeMeInEnv}
      email: ${MANAGER_EMAIL:manager@epms.com}
